root: true
extends:
  - "plugin:drizzle/recommended"
  - "next/core-web-vitals"
  - "next/typescript"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - drizzle
rules:
  "drizzle/enforce-delete-with-where": "error"
  "drizzle/enforce-update-with-where": "error"
